import type { Tool } from './tools';

export const imageTools: Tool[] = [
  {
    id: 'compress-image',
    name: 'Compress Image',
    description: 'Reduce image file size while maintaining quality',
    href: '/image/compress-image',
    color: '#27ae60',
    icon: '<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="#27ae60" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="17 8 12 3 7 8"/><line x1="12" y1="3" x2="12" y2="15"/></svg>',
    iconClass: 'icon-img-compress',
    acceptTypes: '.jpg,.jpeg,.png,.webp',
    multiple: true,
    category: 'image',
    fields: [
      {
        name: 'quality',
        label: 'Quality',
        type: 'range',
        defaultValue: '80',
        min: 10,
        max: 100,
        step: 5,
      },
    ],
  },
  {
    id: 'resize-image',
    name: 'Resize Image',
    description: 'Change image dimensions to any size',
    href: '/image/resize-image',
    color: '#3498db',
    icon: '<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="#3498db" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="15 3 21 3 21 9"/><polyline points="9 21 3 21 3 15"/><line x1="21" y1="3" x2="14" y2="10"/><line x1="3" y1="21" x2="10" y2="14"/></svg>',
    iconClass: 'icon-img-resize',
    acceptTypes: '.jpg,.jpeg,.png,.webp,.bmp',
    multiple: false,
    category: 'image',
    fields: [
      {
        name: 'width',
        label: 'Width (px)',
        type: 'number',
        placeholder: 'e.g. 1920',
        required: true,
      },
      {
        name: 'height',
        label: 'Height (px)',
        type: 'number',
        placeholder: 'e.g. 1080',
        required: true,
      },
    ],
  },
  {
    id: 'crop-image',
    name: 'Crop Image',
    description: 'Crop your image to the perfect size with an interactive editor',
    href: '/image/crop-image',
    color: '#e67e22',
    icon: '<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="#e67e22" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M6 2v14a2 2 0 0 0 2 2h14"/><path d="M18 22V8a2 2 0 0 0-2-2H2"/></svg>',
    iconClass: 'icon-img-crop',
    acceptTypes: '.jpg,.jpeg,.png,.webp,.bmp',
    multiple: false,
    category: 'image',
  },
  {
    id: 'convert-to-jpg',
    name: 'Convert to JPG',
    description: 'Convert PNG, WebP, BMP images to JPG format',
    href: '/image/convert-to-jpg',
    color: '#f39c12',
    icon: '<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="#f39c12" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"/><circle cx="8.5" cy="8.5" r="1.5"/><polyline points="21 15 16 10 5 21"/></svg>',
    iconClass: 'icon-img-to-jpg',
    acceptTypes: '.png,.webp,.bmp,.tiff,.gif',
    multiple: true,
    category: 'image',
    fields: [
      {
        name: 'quality',
        label: 'JPG Quality',
        type: 'range',
        defaultValue: '92',
        min: 10,
        max: 100,
        step: 1,
      },
    ],
  },
  {
    id: 'convert-from-jpg',
    name: 'Convert from JPG',
    description: 'Convert JPG images to PNG or WebP format',
    href: '/image/convert-from-jpg',
    color: '#9b59b6',
    icon: '<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="#9b59b6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"/><circle cx="8.5" cy="8.5" r="1.5"/><polyline points="21 15 16 10 5 21"/></svg>',
    iconClass: 'icon-img-from-jpg',
    acceptTypes: '.jpg,.jpeg',
    multiple: true,
    category: 'image',
    fields: [
      {
        name: 'format',
        label: 'Output Format',
        type: 'select',
        options: [
          { value: 'png', label: 'PNG (lossless)' },
          { value: 'webp', label: 'WebP (smaller size)' },
        ],
        defaultValue: 'png',
      },
    ],
  },
  {
    id: 'webp-to-jpg',
    name: 'WebP to JPG',
    description: 'Convert WebP images to widely compatible JPG format',
    href: '/image/webp-to-jpg',
    color: '#1abc9c',
    icon: '<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="#1abc9c" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/></svg>',
    iconClass: 'icon-img-webp-to-jpg',
    acceptTypes: '.webp',
    multiple: true,
    category: 'image',
  },
  {
    id: 'heic-to-jpg',
    name: 'HEIC to JPG',
    description: 'Convert iPhone HEIC/HEIF photos to JPG',
    href: '/image/heic-to-jpg',
    color: '#e74c3c',
    icon: '<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="#e74c3c" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="5" y="2" width="14" height="20" rx="2" ry="2"/><line x1="12" y1="18" x2="12.01" y2="18"/></svg>',
    iconClass: 'icon-img-heic-to-jpg',
    acceptTypes: '.heic,.heif',
    multiple: true,
    category: 'image',
  },
  {
    id: 'upscale-image',
    name: 'Upscale Image',
    description: 'Enhance image resolution with AI-powered upscaling',
    href: '/image/upscale-image',
    color: '#8e44ad',
    icon: '<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="#8e44ad" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/><line x1="11" y1="8" x2="11" y2="14"/><line x1="8" y1="11" x2="14" y2="11"/></svg>',
    iconClass: 'icon-img-upscale',
    acceptTypes: '.jpg,.jpeg,.png,.webp',
    multiple: false,
    category: 'image',
  },
  {
    id: 'watermark-image',
    name: 'Image Watermark',
    description: 'Add a text watermark to your images',
    href: '/image/watermark-image',
    color: '#2c3e50',
    icon: '<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="#2c3e50" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>',
    iconClass: 'icon-img-watermark',
    acceptTypes: '.jpg,.jpeg,.png,.webp',
    multiple: true,
    category: 'image',
    fields: [
      {
        name: 'text',
        label: 'Watermark Text',
        type: 'text',
        placeholder: 'e.g. CONFIDENTIAL',
        required: true,
      },
    ],
  },
  {
    id: 'rotate-image',
    name: 'Rotate Image',
    description: 'Rotate images by 90, 180, or 270 degrees',
    href: '/image/rotate-image',
    color: '#16a085',
    icon: '<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="#16a085" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="23 4 23 10 17 10"/><path d="M20.49 15a9 9 0 1 1-2.12-9.36L23 10"/></svg>',
    iconClass: 'icon-img-rotate',
    acceptTypes: '.jpg,.jpeg,.png,.webp,.bmp',
    multiple: true,
    category: 'image',
    fields: [
      {
        name: 'angle',
        label: 'Rotation Angle',
        type: 'select',
        options: [
          { value: '90', label: '90° clockwise' },
          { value: '180', label: '180°' },
          { value: '270', label: '90° counter-clockwise' },
        ],
        defaultValue: '90',
      },
    ],
  },
  {
    id: 'blur-face',
    name: 'Blur Face',
    description: 'Automatically detect and blur faces in photos for privacy',
    href: '/image/blur-face',
    color: '#c0392b',
    icon: '<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="#c0392b" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>',
    iconClass: 'icon-img-blur-face',
    acceptTypes: '.jpg,.jpeg,.png,.webp',
    multiple: false,
    category: 'image',
  },
];

export function getImageToolById(id: string): Tool | undefined {
  return imageTools.find((t) => t.id === id);
}
